# Generated by Django 5.2.4 on 2025-07-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
