# Generated by Django 5.2.4 on 2025-07-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='parsed',
            new_name='parsed_data',
        ),
        migrations.AddField(
            model_name='transcript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('done', '완료'), ('error', '오류')], default='pending', max_length=10),
        ),
    ]
