# Generated by Django 4.2.23 on 2025-07-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_rename_parsed_transcript_parsed_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transcripts/pages/')),
                ('page_number', models.PositiveIntegerField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='transcripts.transcript')),
            ],
        ),
    ]
