# Generated by Django 4.2.23 on 2025-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('total_required', models.IntegerField(default=132)),
                ('major_required', models.IntegerField(default=50)),
                ('general_required', models.IntegerField(default=8)),
                ('drbol_required', models.IntegerField(default=18)),
                ('special_general_required', models.IntegerField(default=3)),
                ('sw_required', models.IntegerField(default=9)),
                ('msc_required', models.IntegerField(default=23)),
                ('major_must_courses', models.JSONField(help_text='전공필수 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}')),
                ('major_selective_courses', models.JSONField(blank=True, help_text='전공선택 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('general_must_courses', models.JSONField(blank=True, help_text='교양필수 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('general_selective_courses', models.JSONField(blank=True, help_text='일반선택(교양선택) 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('special_general_courses', models.JSONField(blank=True, help_text='특성화교양 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('sw_courses', models.JSONField(blank=True, help_text='SW/데이터활용역량 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('msc_courses', models.JSONField(blank=True, help_text='MSC 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True)),
                ('drbol_areas', models.TextField(blank=True, help_text="(레거시) 드볼 영역 이름(콤마 구분). 예: '인문과예술,사회와문화,자연과기술'", null=True)),
                ('drbol_rules', models.JSONField(blank=True, help_text='드볼 영역 규칙(JSON). 각 항목: {area, required_credit}', null=True)),
                ('drbol_courses', models.JSONField(blank=True, help_text='드볼 영역별 과목 리스트(JSON). 키=area, 값=과목 배열(각 항목: {code, name, semester?, aliases?})', null=True)),
            ],
            options={
                'unique_together': {('major', 'year')},
            },
        ),
    ]
